@extends('../template/layout')
@section('ogmeta')
    <meta property="og:url" content="{{ route('home') }}/">
    @if(App::isLocale('ru'))
        <meta property="og:title" content="Einsteiners - Сервис организации мероприятий">
        <meta property="og:description" content="Einsteiners - Сервис организации мероприятий">
    @else
        <meta property="og:title" content="Einsteiners - Event Management Service">
        <meta property="og:description" content="Einsteiners - Event Management Service">
    @endif
    <meta property="og:image" content="{{ route('home') }}/images/ogimage.jpg">
@endsection
@section('header-style')

@endsection
@section('stylesheet')
    
@endsection
@section('header')
    @if(App::isLocale('ru'))
        <title>Условия использования</title>
        {{--
        <meta name="description" content="Описание"/>
        <meta name="keywords" content="Ключевые слова"/>
        --}}  
    @else
        <title>Terms of use</title>
        {{--
        <meta name="description" content="Описание"/>
        <meta name="keywords" content="Ключевые слова"/>
        --}}
    @endif
@endsection
@section('style')
<style>

</style>
@endsection
@section('content')
<div class="uk-screen uk-screen-page uk-screen-create">
    <div class="uk-container uk-container-center">
        @if(App::isLocale('ru'))
            <h1>Условия использования</h1>
            <hr />
            <h3>1. Сфера применения</h3>
            <p>Настоящие правила и условия использования регулируют отношения использования между операторами einsteiners.us.de или einsteiners.us.net (далее именуемый как einsteiners.us ) и его пользователей (далее именуемый Пользователь). Предоставляемые услуги предназначены исключительно для частных лиц. einsteiners.us не может использоваться для рекламы или SEO-мер (т.е., например, для размещения ссылок на другой онлайн-контент для повышения рейтинга в поисковых системах). einsteiners.us оставляет за собой право изменять или удалять части предлагаемых услуг в любое время и без предварительного уведомления. Отклоняющиеся или дополнительные положения и условия использования или соглашения требуют явного и письменного согласия от einsteiners.us .</p>
            <h3>2. Объект использования</h3>
            <p>einsteiners.us предоставляет пользователю сервис для создания и администрирования онлайн-списков пожеланий. Добавление пожеланий в список пожеланий пользователя осуществляется пользователем лично. Однако, einsteiners.us оставляет за собой право вносить предложения по пожеланиям, вставляя изображения и тексты.<br /> После создания списка пожеланий пользователю отображаются два отдельных URL-адреса, по которым он может управлять своим списком пожеланий (далее - URL администрирования) или просматривать его (далее - URL просмотра). <br /> Отправив URL-адрес просмотра третьим лицам (например по электронной почте), Пользователь может предоставить созданный им список пожеланий сторонним пользователям (например, друзьям и родственникам) для просмотра. С помощью этого представления сторонние пользователи могут “резервировать” пожелания в списке пожеланий (далее - функция резервирования). При резервировании желанию присваивается соответствующая отметка резервирования в представлении. Бронирование может быть отменено повторно позже только в том случае, если лицо, сделавшее бронирование, при бронировании укажет свой адрес электронной почты. В результате этого адреса электронной почты лицо, сделавшее бронирование, идентифицируется при отмене бронирования. Для окончательной отмены бронирования лицу, сделавшему бронирование, высылается ссылка по электронной почте, с помощью которой он затем может отменить бронирование. Функция бронирования может быть включена и выключена Пользователем по адресу администрации по своему усмотрению. <br />Для отправки URL-адреса просмотра, einsteiners.us предоставляет интегрированные функции, позволяющие делать это через Facebook (www.facebook.com ), Твиттер (www.twitter.com ) или через WhatsApp (www.whatsapp.com ). Для такого использования этих функций необходимо отдельное согласие Пользователя в условиях использования данного сервиса. Без этого согласия рассматриваемая функция не может быть использована. <br />einsteiners.us может представлять Пользователю услуги и продукты других поставщиков (реклама). einsteiners.us не несет ответственности за предлагаемые услуги и продукты. einsteiners.us поэтому не несет никакой ответственности за правильное предоставление или предоставление услуг и/ или продуктов, предлагаемых поставщиком. <br />Услуги, предлагаемые einsteiners.us это онлайн-сервисы, которые, соответственно, могут использоваться исключительно через Интернет и с соответствующими устройствами. einsteiners.us оставляет за собой право расширять и изменять предлагаемые услуги в любое время и в любом объеме, а также больше не предлагать их. Предварительное уведомление Пользователя не требуется. Кроме того, некоторые или все услуги могут быть временно недоступны по техническим причинам или в связи с форс-мажорными обстоятельствами.</p>
            <h3>3. Используйте отношения</h3>
            <p>Отношения использования возникают в результате создания пользователем нового списка пожеланий. Для создания списка пожеланий для списка пожеланий можно ввести дополнительные параметры, такие как имя или описание. Аналогичным образом, можно оставить адрес электронной почты, на который будет отправлено письмо с подтверждением после создания списка пожеланий. <br /> При регистрации или создании списка пожеланий и вводе адреса электронной почты Пользователь утверждает einsteiners.us получив разрешение отправить ему письмо с подтверждением на указанный адрес электронной почты. Отправка дальнейших новостей и информации об улучшениях продукта требует явного согласия Пользователя. Это согласие должно быть подтверждено в форме процесса двойной регистрации путем перехода по ссылке подтверждения, которую Пользователь получает по электронной почте, отправленной на указанный адрес электронной почты.</p>
            <h3>4. Ответственность и убытки</h3>
            <p>Пользователь обязуется, в частности, хранить адрес администрации в секрете и использовать его только по назначению, то есть для личного администрирования списка пожеланий самим Пользователем. einsteiners.us не несет ответственности за все и любые убытки, которые могут быть вызваны неправильным использованием URL-адреса администрации, а также URL-адреса просмотра третьими лицами.<br /> Пользователь обязуется использовать функцию привязки пожеланий только по ее первоначальной цели, т.е. связывать пожелания с более подробной информацией о продукте или возможностями покупки, например, в интернет-магазинах. einsteiners.us оставляет за собой право удалить ссылку из пожеланий, ссылка на которые не служит цели, описанной здесь, удалить пожелание, а также удалить или заблокировать весь список пожеланий.<br /> Пользователь несет личную ответственность за оформление своего списка пожеланий с фотографиями и текстами. einsteiners.us не несет ответственности за фотографии или тексты, используемые Пользователем. einsteiners.us также не несет ответственности за контент, на который ссылается Пользователь.<br /> Пользователю не разрешается размещать ссылки на незаконный контент через свой список пожеланий или распространять их иным образом, например путем сопоставления отрывков текста.<br /> einsteiners.us не несет ответственности за ущерб, причиненный использованием или неиспользованием предоставляемых услуг. Вместо этого Пользователь осознает тот факт, что предлагаемые услуги являются программным обеспечением, которое в принципе может быть неисправным. Аналогично, einsteiners.us не несет ответственности за ущерб системам Пользователя (компьютерам, мобильным телефонам и т.д.) или хранящимся на них данным, вызванный взаимодействием Пользователя или этих систем с einsteiners.us услуги.<br /> einsteiners.us не несет ответственности за ущерб, причиненный законным или незаконным использованием третьими лицами, например путем законного или незаконного доступа к URL-адресу просмотра или списку пожеланий.<br /> einsteiners.us не несет ответственности за ущерб и потерю возможности использования в случае сбоя услуг. einsteiners.us не несет ответственности за онлайн-контент на интернет-сайтах третьих лиц, на которые ссылаются einsteiners.us . Ответственность за них несут исключительно операторы соответствующих сайтов, на которые даны ссылки.</p>
            <h3>5. Обязанность пользователей по возмещению ущерба</h3>
            <p>Пользователь обязан полностью возместить ущерб, причиненный виновным поведением с его стороны.</p>
            <h3>6. Окончание использования</h3>
            <p> Списки пожеланий, созданные Пользователем с помощью einsteiners.us может быть удален им в любое время. Таким образом, полный список пожеланий, включающий введенные (личные) данные и соответствующие пожелания, будет безвозвратно удален из базы данных. Далее, einsteiners.us оставляет за собой право удалять списки пожеланий из базы данных по истечении соответствующего периода времени, который должен составлять не менее одного года, без предварительного уведомления Пользователя. einsteiners.us аналогичным образом оставляет за собой право преждевременно удалять списки пожеланий, если Пользователь бросается в глаза в результате вредного поведения или нарушения пунктов настоящих правил и условий использования.</p>
            <h3>7. Защита данных</h3>
            <p>Принимая во внимание § 14, подраздел 2 Закона Германии о средствах массовой информации, einsteiners.us обязуется не передавать третьим лицам данные, которые могли бы указать на личность Пользователя. Однако Пользователь осознает тот факт, что нельзя исключать, что третьи стороны могут получить несанкционированный доступ к этим данным во время передачи данных в Интернете.<br /> Подробные правила защиты данных можно найти в Заявлении о конфиденциальности.</p>
            <h3>8. Изменения</h3>
            <p>einsteiners.us оставляет за собой право изменять настоящие правила и условия использования в любое время. Изменения не должны быть обоснованы по отношению к Пользователю, в частности, однако, изменения могут быть внесены в той мере, в какой предложение предоставляемых услуг расширяется или сокращается.</p>
            <h3>9. Положение о разделяемости</h3>
            <p> Если части настоящих правил и условий использования являются недействительными или неэффективными, остальные части остаются неизменными.</p>
        @else
            <h1>Terms of use</h1>
            <hr />
            <h3>1. Scope of application</h3>
            <p>The present terms and conditions of use regulate the use relationship between the operators of einsteiners.us.de or einsteiners.us.net (hereinafter referred to as einsteiners.us) and its users (hereinafter referred to as User). The services provided are exclusively intended for private persons. einsteiners.us may not be used for advertising or SEO measures (i.e., for example for linking of other online contents to increase search engine rankings). einsteiners.us reserves the right to amend or to delete parts of the services on offer at any time and without prior notification. Deviating or supplementary terms and conditions of use or agreements shall require express and written consent from einsteiners.us.</p>
            <h3>2. Object of use</h3>
            <p>einsteiners.us provides User with a service for the production and administration of online wish lists. Addition of wishes to a user’s wish list is done by the user personally. However, einsteiners.us reserves the right to to make suggestions for wishes by inserting images and texts.<br /> After a wish list has been created, user is shown two individual URLs via which he can administer his wish list (hereinafter administration URL) or view it (hereinafter view URL). <br />By sending the view URL to third parties (e.g. by e-mail), User can provide the wish list he had produced to third-party users (e.g. friends and relatives) to look at. Via this view, the third-party users can “reserve” wishes on the wish list (hereinafter reservation function). With a reservation, the wish is given a matching reservation marking in the view. A reservation can only be cancelled again later if the reserving person inputs his e-mail address when making the reservation. As a result of this e-mail address, the reserving person is identified when the reservation is cancelled. For a final cancellation of the reservation, the reserving person is sent a link by e-mail, via which he can then cancel the reservation. The reservation function can be switched on and off by User via the administration URL as he wishes. <br />For the dispatch of the view URL, einsteiners.us provides integrated functions to be able to do this via Facebook (www.facebook.com), Twitter (www.twitter.com) or via WhatsApp (www.whatsapp.com). For this use of these functions, separate consent of User in the terms and conditions of use of the service in question is necessary. Without this consent, the function in question cannot be used. <br />einsteiners.us can present services and products from other providers to User (advertising). einsteiners.us is not answerable for the services and products offered. einsteiners.us therefore assumes no liability for the correct rendering or supply of the services and/or products offered by the provider. <br />The services offered by einsteiners.us are online services which accordingly can exclusively be used via the internet and with matching appliances. einsteiners.us reserves the right to extend and to change the services on offer at any time and to any scope or also no longer to offer them. Prior notification of User need not be given. In addition, parts of or all services may temporarily no longer be available for technical reasons or due to force majeure.</p>
            <h3>3. Use relationships</h3>
            <p>A use relationship comes about by the creation of a new wish list by a user. For the creation of a wish list, optional parameters such as a name or a description can be input for the wish list. Likewise, an e-mail address can be left, with a confirmation mail being sent to it following the creation of the wish list. <br />With registration or creation of a wish list and input of an e-mail address, User approves einsteiners.us being allowed to send him a confirmation mail to the e-mail address stated. Dispatch of further news and information about product improvements shall require User’s express consent. This consent shall be confirmed in the form of a double opt-in process by access to a confirmation link, which User receives in an e-mail sent to the e-mail address stated.</p>
            <h3>4. Liability and damages</h3>
            <p>User undertakes in particular to keep the administration URL secret and only to use it for the intended purpose, i.e. personal administration of the wish list by User himself. einsteiners.us shall assume no liability for all and any damages which may be caused by misuse of the administration URL, but also the view URL, by third parties.<br /> User undertakes only to use the linking function of wishes for its original purpose, i.e. linking of a wish with further-reaching product information or possibilities of purchase, e.g. in online shops. einsteiners.us reserves the right to remove the linking from wishes, the linking of which does not serve the purpose described here, to delete the wish or also to delete or to block the entire wish list.<br /> User is personally responsible for the design of his wish list with photos and texts. einsteiners.us shall not be responsible for the photos or texts used by User. einsteiners.us shall likewise not be liable for the contents linked by User.<br /> User shall not be allowed to link illegal contents via his wish list or to propagate them otherwise, e.g. by matching text excerpts.<br /> einsteiners.us shall not be liable for damage caused by the use or the non-use of the services provided. Instead, User is conscious of the fact that the services offered are software, which may principally be defective. Likewise, einsteiners.us is not liable for damage to User’s systems (computers, cell phones etc.) or to the data stored on them caused by User’s or these systems’ interactions with the einsteiners.us services.<br /> einsteiners.us shall not be liable for damage caused by legitimate or illegitimate use by third parties, e.g. by legitimate or illegitimate access to the view URL or a wish list.<br /> einsteiners.us shall not be liable for damage and the loss of use if the services fail. einsteiners.us shall not be liable for the online contents on third parties’ internet sites linked by einsteiners.us. The operators of the linked sites in question shall exclusively be liable for them.</p>
            <h3>5. Users duty to damages</h3>
            <p>User is obliged to complete indemnification of damage caused by culpable conduct on his part.</p>
            <h3>6. End of use</h3>
            <p>Wish lists produced by User via einsteiners.us can be deleted by him at any time. In this way, the complete wish list including the (personal) data input and the matching wishes shall be irrevocably deleted in the database. Further, einsteiners.us reserves the right to delete the wish lists from the database after a suitable period of time, which shall be no less than one year, without prior notification of User. einsteiners.us likewise reserves the right to delete wish lists prematurely if User is conspicuous as a result of damaging conduct or breaching points of these terms and conditions of use.</p>
            <h3>7. Data protection</h3>
            <p>Taking § 14, subsection 2, German Tele-Media Act into due account, einsteiners.us undertakes not to forward data which could give an indication of User’s identity to third parties. However, User is conscious of the fact that it cannot be ruled out that third parties may procure unauthorised access to these data during a transmission of data in the internet.<br /> The extensive regulations of data protection can be found in the Privacy statement.</p>
            <h3>8. Changes</h3>
            <p>einsteiners.us reserves the right to change these terms and conditions of use at any time. The changes need not be substantiated towards User, in particular, however, changes can be made to the extent that the offer of the services provided is extended or reduced.</p>
            <h3>9. Severability clause</h3>
            <p>If parts of these terms and conditions of use are invalid or ineffective, the other parts shall remain unaffected.</p>
        @endif
    </div>
</div>
@endsection