@if(App::isLocale('en'))
    <h2>Политика конфиденциальности</h2>
    <p> Вам необходимо будет предоставить нам Личную информацию, если вы решите использовать определенные функции в нашем Мобильном приложении или на веб-сайте или у нас в магазине. Это включает в себя, когда вы:</p>
    <ul>
        <li>Создайте учетную запись Einsteiners. Чтобы создать учетную запись Einsteiners, вы должны предоставить нам личные идентификаторы, такие как ваше имя, дата рождения и адрес электронной почты. Как только ваша учетная запись будет создана, мы сохраним ваше имя пользователя и пароль Einsteiners.</li>
        <li>Совершите покупку. Если вы совершаете покупку, вам необходимо будет предоставить свои личные идентификаторы, такие как ваше имя, физический адрес и адрес электронной почты, а также информацию о клиенте, записи, включая номер платежной карты. Когда вы совершаете покупку, мы также собираем и храним коммерческую информацию о вас, такую как приобретенные, полученные или рассмотренные продукты, а также тенденции покупки и потребления.</li>
        <li>Участвуйте в социальных сетях. Вы можете поделиться своими личными идентификаторами, такими как ваше имя и любая другая личная информация, которую вы решите включить в свой пост, через наши страницы рейтингов и обзоров, а также страницы в социальных сетях. Если вы помечаете общедоступный пост в социальных сетях ссылкой на Einsteiners, с вашего разрешения, мы также можем собрать ваше изображение, которое вы решите включить в свой пост.</li>
        <li>Взаимодействуйте с нами. Когда вы общаетесь с нами или отправляете нам какие-либо отзывы, вопросы, запросы о поддержке, комментарии, предложения, идеи или каким-либо образом взаимодействуете с нами, вам необходимо будет предоставить персональные идентификаторы, включая ваше имя и адрес электронной почты.</li>
        <li>Подпишитесь на обновления и рекламные акции Einsteiners. У вас есть возможность подписаться на обновления электронной почты Einsteiners или наши ЗАБАВНЫЕ обновления текстовых сообщений для продуктов, услуг и предложений, которые могут вас заинтересовать. Чтобы зарегистрироваться, вам необходимо будет предоставить нам персональные идентификационные данные, такие как ваше имя, адрес электронной почты и / или номер телефона. Когда вы регистрируетесь, мы можем использовать вашу личную информацию, чтобы связаться с вами с помощью информационных бюллетеней, маркетинговых или рекламных материалов и другой информации, которая может вас заинтересовать. Вы можете отказаться от получения любого или всех этих сообщений от нас, перейдя по ссылке для отказа от подписки или инструкциям, приведенным в любом отправленном нами электронном письме.</li>
        <li>Передвигайтесь по нашему магазину. Если вы посетите места расположения Einsteiners, ваше видео будет снято нашими камерами видеонаблюдения.</li>
    </ul>
    <br /><br />
@else
    <h2>Privacy policy</h2>
    <p>You will be required to provide us with Personal Information if you choose to engage with certain functions on our Mobile Application or Website or with us in-store. This includes when you:</p>
    <ul>
        <li>Create an Einsteiners account. To create an Einsteiners account, you will provide us with personal identifiers, such as your name, date of birth, and email address. Once your account is created, we will maintain your Einsteiners username and password.</li>
        <li>Make a purchase. If you make a purchase, you will need to provide your personal identifiers, such as your name, physical address, and email address, as well as customer, records information, including payment card number. When you make a purchase, we also collect and maintain commercial information about you, such as products purchased, obtained, or considered, and purchasing and consuming tendencies.</li>
        <li>Participate in social media. You may choose to share your own personal identifiers, such as your name and any other personal information you choose to include in your post, through our ratings and review pages, and social media pages. If you tag a publicly available social media post with a reference to Einsteiners, with your permission, we may also collect an image of you that you choose to include in your post.</li>
        <li>Interact with us. When you communicate with us or send us any feedback, questions, requests for support, comments, suggestions, ideas, or interact with us in any way, you will need to provide personal identifiers, including your name and email address.</li>
        <li>Subscribe to Einsteiners updates and promotions. You have the option of signing up for Einsteiners email updates or our FUN text message updates for products, services and offers that may be of interest to you. To sign-up, you will need to provide us with personal identifiers such as your name, email address, and/or telephone number. When you sign-up, we may use your personal information to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</li>
        <li>Move around in our store. If you visit Einsteiners locations, video of you will be captured by our CCTV footage.</li>
    </ul>
    <br /><br />
@endif